spring.application.name=activityservice
spring.mongodb.uri=mongodb+srv://aryanmishra12112003:mongolelo123@cluster0.xdywl8h.mongodb.net/Fitness-Activity
spring.data.mongodb.database=Fitness-Activity
server.port=8082