spring.application.name=activity-service
spring.mongodb.uri=mongodb+srv://aryanmishra12112003:mongolelo123@cluster0.xdywl8h.mongodb.net/Fitness-Activity
spring.data.mongodb.database=Fitness-Activity
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8762/eureka/

rabbitmq.exhange.name=fitness.exchange
rabbitmq.queue.name=fitness.queue
rabbitmq.routing.key=fitness.tracking
