spring.application.name=ai-service

eureka.client.service-url.defaultZone=http://localhost:8762/eureka/

server.port=8083

spring.data.mongodb.uri=mongodb+srv://aryanmishra12112003:mongolelo123@cluster0.xdywl8h.mongodb.net/Fitness-Recommendations

spring.data.mongodb.database=Fitness-Recommendations

rabbitmq.exhange.name=fitness.exchange
rabbitmq.queue.name=fitness.queue
rabbitmq.routing.key=fitness.tracking
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest